- key: APPINSIGHTS_CONNECTIONSTRING
  value: "{{servicename}}-APPINSIGHTS-CONNECTIONSTRING"
  type: "keyvault"
- key: MESSAGES_HOST
  value: "{{servicename}}-MESSAGES-HOST"
  type: "keyvault"
- key: MESSAGES_USER
  value: "{{servicename}}-MESSAGES-USER"
  type: "keyvault"
- key: MESSAGES_PASSWORD
  value: "{{servicename}}-MESSAGES-PASSWORD"
  type: "keyvault"
- key: NOTIFY_API_KEY
  value: "{{servicename}}-NOTIFY-API-KEY"
  type: "keyvault"
- key: NOTIFY_TEMPLATE_ID
  value: "{{servicename}}-NOTIFY-TEMPLATE-ID"
  type: "keyvault"