- key: APPINSIGHTS_CONNECTIONSTRING
  value: "{{servicename}}-APPINSIGHTS-CONNECTIONSTRING"
  type: "keyvault"
- key: MESSAGES_HOST
  value: "MESSAGES-HOST"
  type: "keyvault"
- key: MESSAGES_USER
  value: "MESSAGES-USER"
  type: "keyvault"
- key: MESSAGES_PASSWORD
  value: "MESSAGES-PASSWORD"
  type: "keyvault"
- key: NOTIFY_API_KEY
  value: "NOTIFY-API-KEY"
  type: "keyvault"
- key: NOTIFY_TEMPLATE_ID
  value: NOTIFY-TEMPLATE-ID
  type: "keyvault"