#!/usr/bin/env sh
if [ -z "$(docker network ls --filter name=^ffc-sfd$ --format={{.Name}})" ]; then
  echo "Creating ffc-sfd Docker network"
  docker network create ffc-sfd
fi

set -e
projectRoot="$(a="/$0"; a=${a%/*}; a=${a:-.}; a=${a#/}/; cd "$a/.." || return; pwd)"

cd "${projectRoot}"

docker-compose down
docker-compose -f docker-compose.migrate.yaml down
# Ensure container images are up to date
docker-compose -f docker-compose.migrate.yaml run --rm database-up

docker-compose \
  -f docker-compose.yaml \
  -f docker-compose.override.yaml \
  -f docker-compose.link.yaml \
  up $@