#!/usr/bin/env sh
if [ -z "$(docker network ls --filter name=^fcp-sfd$ --format={{.Name}})" ]; then
  echo "Creating ffc-sfd Docker network"
  docker network create fcp-sfd
fi

set -e
projectRoot="$(a="/$0"; a=${a%/*}; a=${a:-.}; a=${a#/}/; cd "$a/.." || return; pwd)"

cd "${projectRoot}"
# Guarantee clean environment
docker-compose down
docker-compose -f docker-compose.migrate.yaml down -v
# Ensure container images are up to date
docker-compose -f docker-compose.migrate.yaml run database-up
docker-compose up --build
